### ISSUE TITLE
Update to Trac 1.4.x

### ISSUE THREAD

**Issue by felixxm** [django/code.djangoproject.com#105]
See [release notes](https://trac.edgewall.org/wiki/TracDev/ReleaseNotes/1.4#MaintenanceReleases).

**Comment by apollo13** [comment]
I'd really like to upgrade, but I think this might get hard because 1.4.x does not seem to allow an easy way to override templates: https://trac.edgewall.org/browser/branches/1.4-stable/trac/web/chrome.py#L1386 This currently puts the default trac templates first in the list, which prevents overriding as far as I can see. In trunk it puts the templates dir from the env first: https://trac.edgewall.org/browser/trunk/trac/web/chrome.py#L745

**Comment by apollo13** [comment]
Since 1.6 will be python 3 only, I'd really like to go via 1.4 first. I wonder if it makes sense to fork trac and fix the few things that needs fixing…

**Comment by apollo13** [comment]
Okay, so I started working on this locally. First and foremost there is one problem: We have some views in there that are requested from the tracdb app in djangoproject.com. We need to rewrite those in a way to be compatible first. Working on it.

**Comment by bmispelon** [comment]
I've taken @apollo13 's work from #146 and added a few more fixes: https://github.com/django/code.djangoproject.com/pull/146

I believe Florian's comments about `tracdb` needing some fixes have been merged: https://github.com/django/djangoproject.com/commit/33093f2ebf2c2ceabbbe301ed238ebad1706f3b9. But I'm not 100% sure, and I can't figure out how to test that (even manually).

Trac seems to finally have a Python3-compatible version, so once this is merged, I would like to try to finally upgrade from Python 2.7 (and Django 1.11) to something a bit less ancient 🦕

**Comment by bmispelon** [comment]
Fixed in #146  Good work everyone! 🚀

**Comment by apollo13** [comment]
Nicely done, thank you Baptiste!
