### ISSUE TITLE
A transition is missing in the navigation bar

### ISSUE THREAD

**Issue by cleverhare** [django/code.djangoproject.com#139]
There is no transition at the navbar of the website, which is making the Django website a more static type of content website. Alongside it shows that the website is fairly outdated.

That's why I would like to add a transition when the user hovers over the navigation bar links and give it a cool 2s transition.

I know its a fairly small issue but I believe it would help to bring life to the Django Website. 

## If the reviewer found it a useful and worthy issue, Do assign me this. I would love to contribute to Django

**Comment by sarahboyce** [comment]
Hi @cleverhare :wave: 
If you would like to contribute to the website, you are probably more interested in this repository: https://github.com/django/djangoproject.com
There are issues in labelled with `good first issue`: https://github.com/django/djangoproject.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
There's lots to do! I'm sure you can find something :muscle: 

There is also a survey currently running where you can give your feedback on the website. :tada: 
Survey: https://docs.google.com/forms/d/e/1FAIpQLSffct3GloikvqzDPDc-IR3phuVMfVl12LoDyoJorIzZGOSV7Q/viewform
Django Forum post: https://forum.djangoproject.com/t/help-us-make-the-djangoproject-com-website-better/21731

This repository is actually very specific for the Django issue tracker, so I think it makes sense to close this issue here :+1:

**Comment by bmispelon** [comment]
Hi everyone,

This website (code.djangoproject.com) tries to reuse the stylesheet of the main site (www.djangoproject.com) as much as possible. Most of its CSS is just trying to undo the styling imposed by Trac itself.

I'm therefore going to close this issue for now and encourage you (as Sarah did just above) to contribute to the main website. The changes there will make it here sooner or later.

Please feel free to reopen the issue or comment if you think I've misunderstood your request, or if the changes you're proposing make sense specifically for this website and not the main one.

Thanks!
