### ISSUE TITLE
Add a notification for accounts without an email address

### ISSUE THREAD

**Issue by timgraham** [django/code.djangoproject.com#39]
It would be useful to add something like a banner notification to Trac for people who don't have an email address in https://code.djangoproject.com/prefs to try to cut down on the number of people who file a ticket and then never follow due to lack of notification.

**Comment by bmispelon** [comment]
It might be possible to do some genshi magic in `trac-env/templates/site.html` (I'm not sure if we have access to the current user object in the template context).

Otherwise, we could always just add another hack to `tickethacks.js` :fire_engine:

**Comment by bmispelon** [comment]
After some fiddling, I found a way to inspect the request object which is passed down to the template (I ended up just putting a `pdb.set_trace()` somewhere in Trac's code).

I'm not so sure that it actually contains enough information to do what we want (approach 1) but it might be because I couldn't get auth working on my local install.

We might have to resort to another tickethack after all :person_frowning:

**Comment by timgraham** [comment]
Please see if https://github.com/django/code.djangoproject.com/pull/59 looks okay.
