### ISSUE TITLE
Inline display of diff code snippets looks weird

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#53]
![25009_ create_user _is_staff true _raises_typeerror_multiple_values_for_keyword_argument_is_staff_ _ _django_-_2015-06-19_23 19 27](https://cloud.githubusercontent.com/assets/6345/8263366/1afaec1c-16da-11e5-8283-589b53836e6e.png)

This happens when you do:

```
{{{#!diff
... diff goes here ...
}}}
```

**Comment by timgraham** [comment]
To reproduce: Try to leave a comment or make a new ticket. The text will be displayed as above. If you click "Preview", the syntax highlighting will be corrected.

I suspect this is a Trac issue that should be fixed upstream, perhaps http://trac.edgewall.org/ticket/8005. I'll leave a comment there.

**Comment by jun66j5** [comment]
That is a issue on code.djangoproject.com. Original issue has been fixed in http://trac.edgewall.org/ticket/10674 on Trac 1.0.3.

I noticed "TypeError: jQuery.loadStyleSheet is not a function" in javascript console when puting diff text in ticket comment on code.djangoproject.com. In the code.djangoproject.com, jQuery 1.9.1 is wrongly loaded. Trac 1.0.x is using jQuery 1.7.x. After blocking ajax.googleapis.com, diff text on auto-preview in ticket comment works fine.

**Comment by timgraham** [comment]
I see that Trac stores functions on the [jQuery object](https://github.com/edgewall/trac/blob/badc67eda85d8441f028f8643ffcba0297b8e551/trac/htdocs/js/trac.js#L140-L161) so even if another copy of jQuery is loaded (regardless of the version), those customizations are lost and this error will happen.

I tried removing the loading of the second jQuery in [main.js](https://github.com/django/code.djangoproject.com/blob/7c6566898409b8300aa60600cc5b579fd84425b1/trac-env/htdocs/js/main.js#L5) but encountered another error in the console that I'm not sure how to fix: `require.js:8 Uncaught Error: Script error for: jquery(…)`.

**Comment by bmispelon** [comment]
Seems like this was fixed. If I had to guess, it was either the cleanup on the js libs in 43d9616be346f8b924491596d4549c8fc8fbaf44 or the Trac upgrade in 9deade14d95521831b335a938d190b06daa0dfc7.
